"""Add Zametka model

Revision ID: 180ed41d5233
Revises: 
Create Date: 2025-06-18 22:51:31.174837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180ed41d5233'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zametka',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('number', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zametka')
    # ### end Alembic commands ###
