"""Delete number field from model

Revision ID: 28c28faee3eb
Revises: a1afa557023c
Create Date: 2025-06-19 20:00:22.798630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c28faee3eb'
down_revision = 'a1afa557023c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zametka', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zametka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
